version: "2.4"
services:

  front_end:
    build: './front_end/'
    volumes:
      - data-volume:/var/www/html/
      - ./config:/var/www/html/openVRE/config

  apache2:
    build: './apache/'
    ports:
      - "8088:80"
    volumes:
      - data-volume:/var/www/html/
      - ./config:/var/www/html/openVRE/config


volumes:
  data-volume:
    
          # config-volume:
          #- ./config:/var/www/html/openVRE/config
          
